# Generated by Django 5.2.1 on 2025-05-26 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_content_content_remove_content_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="title",
            new_name="name",
        ),
    ]
