# Generated by Django 5.2.1 on 2025-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_content_created_at_content_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
