# Generated by Django 5.2.1 on 2025-05-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_content_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
