# Generated by Django 5.2.1 on 2025-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_content_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="difficulty_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="estimated_study_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="content",
            name="key_concepts",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
