# Generated by Django 5.2.1 on 2025-05-29 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("key_concepts", models.JSONField(blank=True, null=True)),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("estimated_study_time", models.IntegerField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "is_deleted"],
                        name="app_content_created_65d383_idx",
                    ),
                    models.Index(
                        fields=["processed", "is_deleted"],
                        name="app_content_process_d5b41f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="app_user_is_acti_8bab0e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("token_count", models.IntegerField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="app_message_session_3d69d4_idx",
                    ),
                    models.Index(
                        fields=["session", "role", "timestamp"],
                        name="app_message_session_167bf7_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["user", "-updated_at", "is_deleted"],
                name="app_convers_user_id_4a82be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["-updated_at", "is_deleted"],
                name="app_convers_updated_8406b7_idx",
            ),
        ),
    ]
