# Generated by Django 5.2.1 on 2025-05-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_conversationsession_user_content_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_text", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("total_chunks", models.IntegerField()),
                ("start_char", models.IntegerField()),
                ("end_char", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="app.content",
                    ),
                ),
            ],
            options={
                "ordering": ["content", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["content", "chunk_index"],
                        name="app_content_content_99012d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="app_content_created_8de1fb_idx"
                    ),
                ],
                "unique_together": {("content", "chunk_index")},
            },
        ),
    ]
